name: Documentation ðŸ“”

on:
  push:
    branches: [main, ci/add-publish-to-pypi-ci-job]

permissions:
  contents: write

jobs:
  docs:
    runs-on: instadeep-ci
    container:
      image: ubuntu:latest

    steps:
      - name: Git setup
        run: |
          apt-get update && apt-get install -y \
          coreutils \
          git
          git config --system --add safe.directory $GITHUB_WORKSPACE

      - name: Checkout code  ðŸ“¦
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Build and publish
        run: |
          uv build
          uv publish --token ${{secrets.PYPI_TOKEN}}
