name: Tests and Linters ðŸ§ª

on:
  push:
    branches: [ main ]
  pull_request:


jobs:
  linters:
    runs-on: instadeep-ci-4
    container:
      image: ubuntu-latest

    steps:
      - name: Checkout code  ðŸ“¦
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Lint
        run: uv run pre-commit run --all-files --verbose

  tests:
    runs-on: instadeep-ci-4
    container:
      image: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Test
        run: uv run pytest
