name: Tests and Linters ğŸ§ª

on:
  push:
    branches: [ main ]
  pull_request:


env:
  MIN_COVERAGE_THRESHOLD: 80
  PR_MIN_COVERAGE_THRESHOLD: 80

jobs:
  linters:
    runs-on: instadeep-ci-4
    container:
      image: ubuntu:latest

    steps:
      - name: setup
        run: |
          apt-get update && apt-get install -y \
          coreutils \
          git
          git config --system --add safe.directory $GITHUB_WORKSPACE

      - name: Checkout code  ğŸ“¦
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Lint
        run: uv run pre-commit run --all-files --verbose

  tests:
    runs-on: instadeep-ci-4
    container:
      image: ubuntu:latest

    steps:
      - name: Checkout code  ğŸ“¦
        uses: actions/checkout@v4

      - name: setup
        run: |
          apt-get update && apt-get install -y \
          coreutils \
          git

      - name: Add safe directory ğŸ”’
        run: git config --system --add safe.directory $GITHUB_WORKSPACE

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Run tests ğŸ§ª
        run: |
          uv run pytest --verbose --cov-report xml:coverage.xml \
                            --cov-report term-missing \
                            --junitxml=pytest.xml \
                            --cov=mlipaudit-open

      - name: Pytest coverage comment ğŸ’¬
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./coverage.xml
          junitxml-path: ./pytest.xml

      - name: Create the Badge ğŸ–ï¸
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 5d35ef2849ae89aa9de3365afc066942
          filename: pytest-coverage-comment.json
          label: Test Coverage
          message: ${{ steps.coverageComment.outputs.coverage }}
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: python

      - name: Verify coverage percentage meets threshold requirement âœ…
        id: total-coverage
        run: |
          apt-get update && apt-get install -y bc
          ACTUAL_COVERAGE=$(echo "${{ steps.coverageComment.outputs.coverage }}" | sed 's/%//')
          if (( $(echo "$ACTUAL_COVERAGE < $MIN_COVERAGE_THRESHOLD" | bc -l) )); then
            echo "âŒ Code coverage $ACTUAL_COVERAGE% is below the required $MIN_COVERAGE_THRESHOLD% threshold."
            exit 1
          else
            echo "âœ… Code coverage requirement met."
          fi

      - name: Check coverage diff for changed code ğŸ”
        run: |
          uvx diff-cover coverage.xml --compare-branch=origin/main --fail-under=$PR_MIN_COVERAGE_THRESHOLD
